### ISSUE TITLE
Not receving emails 

### ISSUE THREAD

**Issue by sakshi678** [RajneeshSingh007/College-Management--Android-App#2]
I have been changed your website address with my website address but Still I am not receiving the verify emails?
Do I need to setup email forwading too?
If yes then how?

**Comment by RajneeshSingh007** [comment]
Hello,

When i used 000webhost for this project, they provide only 10 mail that too
was slow (after 1 or 2 hour got mail verification on email id ) .Due to
this issue, I told my client to show their app on localhost in college.
you can use http://www.toolheap.com/test-mail-server-tool/

above tool works perfectly on localhost.

 For localhost testing follow the below steps :

1. Start Wamp server
2. In cmd run ipconfig command (make sure your pc/laptop is connected to
network lan or wifi) and note the ip of lan/wifi network
3. In android studio, Go to Java/package name/misc/utils/constants/ here
change link address to ip address (which you found from steps 2)
so link will be like this :-
http://some ip/demo/register.php .....etc
4. Browse to c/wamp (64 or 32) /www/create demo folder and paste all php
files inside demo folder.
5. open phpmyadmin(make sure wamp is on) in browser and there you can
create demo database(if you changed database in Config. then create that one
) and inside that import the demo.sql file (download from github )
6. Also, run test mail server tool.
7. Finally Check in emulator/phone (for phone, you should config wamp
to work on phone ).

**Comment by sakshi678** [comment]
Is DB host same all time like if I switch to hostgator should I need to change my DB host or It will be remaining as  local host there also

**Comment by RajneeshSingh007** [comment]
@sakshi678 Yes,you have to change everything in Config.php (there are 3 Config.php ,change in all files). Like host,dbname,dbpassword etc. which you got from hostgator.

Best Regards,
Rajneesh Singh

**Comment by sakshi678** [comment]
Hello Sir Can you Help me to modifying the Project
because me samjh nahi paa rahi and kuch bhi work nahi kar raha...
 aap help kar paoge?

**Comment by RajneeshSingh007** [comment]
@sakshi678 Hello,
you tried localhost method ?. there may be problem of email from hosting provider or need some setup like stmp(try php mailer) for proper email  If you try on localhost using php test mail tool it will work perfectly :)

Best Regards,
Rajneesh Singh

**Comment by sakshi678** [comment]
I am familiar with XAMPP so Can I use xampp instead of wamp?
And Where thr url is written should I write there localhost/login.php or
127.0.0.1/login.php ?
And Version of php should be 5.6 or 7.1 😅

**Comment by RajneeshSingh007** [comment]
@sakshi678 
you can give a try ,also run test mail php tool  for email .
Php version should be 5.6
when you will start wamp or xamp then connect to network via wifi or lan and in cmd type ipconfig..then look for wifi/lan network ip v4 address and add that ip into the url for eg.
http://slrtceapp.000webhost.com/register.php to http://ip addrees (the one you got from ipconfig ip4 address)/login.php
